ACATSociWeb/Controllers/ClubsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ACATSociWeb.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ACATSociWeb.Models;

namespace ACATSociWeb.Controllers
{
  public class ClubsController : Controller
  {
    private readonly ACATSociWebContext _context;
    private readonly IAppContext _iAppContext;

    private dynamic TuttiMembri { get; }

    public ClubsController(ACATSociWebContext context, IAppContext i_AppContext)
    {
      _context = context;
      _iAppContext = i_AppContext;

      IQueryable<string> sociQuery = from m in _context.Socio
                                     orderby m.Cognome
                                     select m.Nome + @" " + m.Cognome;

      try
      {
        TuttiMembri = new SelectList(sociQuery.Distinct().ToList());
      }
      catch (Exception e)
      {
        Console.WriteLine(e);
      }
    }

    // GET: Clubs
    public async Task<IActionResult> Index()
    {
      if (!_iAppContext.IsAuthenticated)
      {
        return RedirectToAction("Authorize", "Login");
      }

      var list = await _context.ClubTorinoEst.ToListAsync();

      var clubsViewModel = new ClubsViewModel();
      clubsViewModel.ListClubsViewModel = new List<ClubViewModel>();
      if (list.Any())
      {
        list.ForEach(i => clubsViewModel.ListClubsViewModel.Add(new ClubViewModel
        {
          CanEdit = _iAppContext.IsAdmin,
          CAT = i
        }));
      }
      clubsViewModel.CanCreateNewClub = _iAppContext.IsAdmin;

      return View(clubsViewModel);
    }

    // GET: Clubs/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var clubTorinoEst = await _context.ClubTorinoEst
          .FirstOrDefaultAsync(m => m.Id == id);
      if (clubTorinoEst == null)
      {
        return NotFound();
      }

      var clubVM = new ClubViewModel
      {
        CanEdit = _iAppContext.IsAdmin,
        CAT = clubTorinoEst,
        Club = clubTorinoEst.Club.ToString()
      };

      return View(clubVM);
    }

    // GET: Clubs/Create
    public IActionResult Create()
    {
      ViewBag.TuttiMembri = TuttiMembri;
      return View();
    }

    // POST: Clubs/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Club,Presidente,Segretario,Tesoriere,ServitoreInsegnante,NumeroTelefonico,Sede,GiornoIncontri,OraInizio,OraFine")] ClubTorinoEst clubTorinoEst)
    {
      if (ModelState.IsValid)
      {
        _context.Add(clubTorinoEst);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      ViewBag.TuttiMembri = TuttiMembri;
      return View(clubTorinoEst);
    }

    // GET: Clubs/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var clubTorinoEst = await _context.ClubTorinoEst.FindAsync(id);
      if (clubTorinoEst == null)
      {
        return NotFound();
      }
      ViewBag.TuttiMembri = TuttiMembri;
      return View(clubTorinoEst);
    }

    // POST: Clubs/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Club,Presidente,Segretario,Tesoriere,ServitoreInsegnante,NumeroTelefonico,Sede,GiornoIncontri,OraInizio,OraFine")] ClubTorinoEst clubTorinoEst)
    {
      if (id != clubTorinoEst.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(clubTorinoEst);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!ClubTorinoEstExists(clubTorinoEst.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }
        return RedirectToAction(nameof(Index));
      }
      return View(clubTorinoEst);
    }

    // GET: Clubs/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var clubTorinoEst = await _context.ClubTorinoEst
          .FirstOrDefaultAsync(m => m.Id == id);
      if (clubTorinoEst == null)
      {
        return NotFound();
      }

      return View(clubTorinoEst);
    }

    // POST: Clubs/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var clubTorinoEst = await _context.ClubTorinoEst.FindAsync(id);
      _context.ClubTorinoEst.Remove(clubTorinoEst);
      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool ClubTorinoEstExists(int id)
    {
      return _context.ClubTorinoEst.Any(e => e.Id == id);
    }

  }
}

ACATSociWeb/Controllers/SociTorinoEstController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ACATSociWeb.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ACATSociWeb.Models;
using Microsoft.Extensions.FileProviders;

namespace ACATSociWeb.Controllers
{
  public class SociTorinoEstController : Controller
  {
    private readonly ACATSociWebContext _context;
    private readonly IFileProvider _iFileProvider;
    private readonly IAppContext _iAppContext;
    private SelectList TuttiClub { get; }

    public SociTorinoEstController(ACATSociWebContext context, IFileProvider i_FileProvider, IAppContext i_AppContext)
    {
      _context = context;
      _iFileProvider = i_FileProvider;
      _iAppContext = i_AppContext;

      IQueryable<string> clubsQuery = from m in _context.ClubTorinoEst
        orderby m.Club
        select m.Club;

      try
      {
        TuttiClub = new SelectList(clubsQuery.Distinct().ToList());
      }
      catch (Exception e)
      {
        Console.WriteLine(e);
      }
    }


    // GET: SociTorinoEst
    public IActionResult Index(string socioClub, string ruoloClub, string searchString)
    {
      if (!_iAppContext.IsAuthenticated)
      {
        return RedirectToAction("Authorize", "Login");
      }

      DateTimeOffset lastModifiedDate = _iFileProvider.GetFileInfo(@"Views\SociTorinoEst\Index.cshtml").LastModified;
      ViewData["LastModified"] = lastModifiedDate;

      var socioClubVM = GetSocioClubViewModel(socioClub, ruoloClub, searchString);

      return View(socioClubVM);
    }

    // GET: SociTorinoEst/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var socio = await _context.Socio
          .FirstOrDefaultAsync(m => m.Id == id);

      var clubTorinoEst = await _context.ClubTorinoEst.FirstOrDefaultAsync(m => m.Club == socio.CatDiAppartenenza);

      if (socio == null)
      {
        return NotFound();
      }

      var clubVM = new ClubViewModel
      {
        CanEdit = _iAppContext.IsAdmin || _iAppContext.AuthorizedUser.Id == socio.Id,
        Socio = socio,
        CAT = clubTorinoEst
      };

      return View(clubVM);
    }

    private SocioClubViewModel GetSocioClubViewModel(string socioClub, string ruoloClub, string searchString)
    {
      // Use LINQ to get list 
      IQueryable<string> clubsQuery = from m in _context.Socio
        orderby m.CatDiAppartenenza
        select m.CatDiAppartenenza;

      // Use LINQ to get list 
      IQueryable<RuoliSocio> ruoliQuery = from m in _context.Socio
        orderby m.RuoloAlCat
        select m.RuoloAlCat;

      var soci = from m in _context.Socio select m;

      if (!string.IsNullOrEmpty(searchString))
      {
        soci = soci.Where(s => s.Cognome.Contains(searchString) || s.Nome.Contains(searchString));
      }

      if (!string.IsNullOrEmpty(socioClub))
      {
        soci = soci.Where(s => s.CatDiAppartenenza.ToString() == socioClub);
      }

      if (!string.IsNullOrEmpty(ruoloClub))
      {
        soci = soci.Where(s => s.RuoloAlCat.ToString() == ruoloClub);
      }

      try
      {
        var cc = soci.ToList();
      }
      catch (Exception e)
      {
        soci = new EnumerableQuery<Socio>(new List<Socio>());
      }

      var socioClubVM = new SocioClubViewModel
      {
        Clubs = new SelectList(clubsQuery.Distinct().ToList()),
        Ruoli = new SelectList(ruoliQuery.Distinct().ToList()),
        Soci = soci.ToList(),
        SocioClub = socioClub?? string.Empty,
        RuoloClub = ruoloClub?? string.Empty,
        SearchString = searchString?? string.Empty,
        CanEdit = _iAppContext.IsAdmin,
        AuthenticatedUser = _iAppContext.AuthorizedUser
      };

      return socioClubVM;
    }

    // GET: SociTorinoEst/Create
    public IActionResult Create()
    {
      ViewBag.TuttiClub = TuttiClub;
      return View();
    }

    // GET: SociTorinoEst/Register
    public IActionResult Register()
    {
      ViewBag.TuttiClub = TuttiClub;
      return View();
    }

    // POST: SociTorinoEst/Register
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Register([Bind("Id,Cognome,Nome,Qualifica,Nazionalita,ComuneDiNascita_Stato,Provincia,DataDiNascita,IndirizzoDiResidenza,ComuneDiResidenza,ProvinciaDiResidenza,CAP,Cellulare,Email,CodiceFiscale,CatDiAppartenenza,DataIscrizioneCat,RuoloAlCat")] Socio socio)
    {
      if (ModelState.IsValid)
      {
        var exists = await _context.Socio.FirstOrDefaultAsync(m => m.CodiceFiscale.Equals(socio.CodiceFiscale));
        if (exists == null)
        {
          _context.Add(socio);
          await _context.SaveChangesAsync();

          var newSocio = await _context.Socio.FirstOrDefaultAsync(m => m.Nome.Equals(socio.Nome, StringComparison.CurrentCultureIgnoreCase) && m.Cognome.Equals(socio.Cognome, StringComparison.CurrentCultureIgnoreCase));
          if (newSocio != null)
          {
            _iAppContext.AuthorizedUser = newSocio;
            _iAppContext.IsAuthenticated = true;
            _iAppContext.IsAdmin = false;
            return RedirectToAction("Details", new{Id = newSocio.Id});
          }
        }
      }
      ViewBag.TuttiClub = TuttiClub;
      return View(socio);
    }

    // POST: SociTorinoEst/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Cognome,Nome,Qualifica,Nazionalita,ComuneDiNascita_Stato,Provincia,DataDiNascita,IndirizzoDiResidenza,ComuneDiResidenza,ProvinciaDiResidenza,CAP,Cellulare,Email,CodiceFiscale,CatDiAppartenenza,DataIscrizioneCat,RuoloAlCat")] Socio socio)
    {
      if (ModelState.IsValid)
      {
        var exists = await _context.Socio.FirstOrDefaultAsync(m => m.CodiceFiscale.Equals(socio.CodiceFiscale));
        if (exists == null)
        {
          _context.Add(socio);
          await _context.SaveChangesAsync();
          return RedirectToAction(nameof(Index));
        }
      }
      ViewBag.TuttiClub = TuttiClub;
      return View(socio);
    }

    // GET: SociTorinoEst/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var socio = await _context.Socio.FindAsync(id);
      if (socio == null)
      {
        return NotFound();
      }
      ViewBag.TuttiClub = TuttiClub;
      return View(socio);
    }

    // POST: SociTorinoEst/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Cognome,Nome,Qualifica,Nazionalita,ComuneDiNascita_Stato,Provincia,DataDiNascita,IndirizzoDiResidenza,ComuneDiResidenza,ProvinciaDiResidenza,CAP,Cellulare,Email,CodiceFiscale,CatDiAppartenenza,DataIscrizioneCat,RuoloAlCat")] Socio socio)
    {
      if (id != socio.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(socio);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!SocioExists(socio.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }
        return RedirectToAction(nameof(Index));
      }
      ViewBag.TuttiClub = TuttiClub;
      return View(socio);
    }

    // GET: SociTorinoEst/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var socio = await _context.Socio
          .FirstOrDefaultAsync(m => m.Id == id);
      if (socio == null)
      {
        return NotFound();
      }

      return View(socio);
    }

    // POST: SociTorinoEst/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var socio = await _context.Socio.FindAsync(id);
      _context.Socio.Remove(socio);
      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool SocioExists(int id)
    {
      return _context.Socio.Any(e => e.Id == id);
    }

    public IActionResult ExportExcel(string socioClub, string ruoloClub, string searchString)
    {
      var vm = GetSocioClubViewModel(socioClub, ruoloClub, searchString);
      return View(vm);
    }
  }
}

ACATSociWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - Torino Est</title>

  <environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
          crossorigin="anonymous"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
  </environment>
  <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  <header>
    <img src="\Banner.JPG" />
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <a class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
           aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggle-icon">
            <svg width="24" height="24" viewBox="0 0 24 24">
              <path d="M3,17H21V15H3V17M3,20H21V19H3V20M3,13H21V10H3V13M3,4V8H21V4H3Z" />
            </svg>Menu
          </span>
        </a>
        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="nav-item">
              <b><a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a></b>
            </li>
            <li class="nav-item">
              <b><a class="nav-link text-dark" asp-area="" asp-controller="Clubs" asp-action="Index">Elenco Club</a></b>
            </li>
            <li class="nav-item">
              <b> <a class="nav-link text-dark" asp-area="" asp-controller="SociTorinoEst" asp-action="Index">Elenco Soci</a></b>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <partial name="_CookieConsentPartial" />
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <style>
    p.Center {
      font-size: 15px;
      text-align: center;
      font-style: italic
    }
    p.Right {
      font-size: 15px;
      text-align: right;
      font-style: italic
    }
  </style>

  <footer class="border-top footer text-muted">
    <p class="Center">Soci Web - by Dario Pellegrini - &copy; 2020 </p>
  </footer>

  <environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
  </environment>
  <environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
  </environment>
  <script src="~/js/site.js" asp-append-version="true"></script>

  @RenderSection("Scripts", required: false)
</body>
</html>